# Generated by Django 5.2.5 on 2025-08-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_aboutmeexperiences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmeexperiences',
            name='description',
            field=models.TextField(max_length=512),
        ),
    ]
