# Generated by Django 5.2.5 on 2025-08-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_aboutmeexperiences_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='static/media')),
                ('github_link', models.URLField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
