# Generated by Django 5.2.5 on 2025-08-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_certificationcategory_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='certificationcategory',
            name='description',
        ),
    ]
