# Generated by Django 5.2.5 on 2025-08-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_certification_date_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(upload_to='static/media'),
        ),
    ]
