# Generated by Django 5.2.5 on 2025-08-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_certification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutmeexperiences',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certification',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='aboutmeexperiences',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/media'),
        ),
    ]
