# Generated by Django 5.2.5 on 2025-08-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_aboutme_image_url_aboutmeexperiences_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
