# Generated by Django 5.2.5 on 2025-08-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
