# Generated by Django 5.2.5 on 2025-08-24 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_project_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='language',
        ),
    ]
