# Generated by Django 5.2.5 on 2025-08-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='more_experiences/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='more_experiences/videos/')),
                ('is_video', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'More Experience',
                'verbose_name_plural': 'More Experiences',
                'ordering': ['id'],
            },
        ),
    ]
