# Generated by Django 5.2.5 on 2025-08-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_moreexperience'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moreexperience',
            options={},
        ),
        migrations.RemoveField(
            model_name='moreexperience',
            name='image',
        ),
        migrations.RemoveField(
            model_name='moreexperience',
            name='video',
        ),
        migrations.AddField(
            model_name='moreexperience',
            name='button_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moreexperience',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
