# Generated by Django 5.2.5 on 2025-08-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_moreexperience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreexperience',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
