# Generated by Django 5.2.5 on 2025-11-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_moreexperience_button_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='image_url',
            new_name='button_url',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='button_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='is_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='media_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=models.TextField(),
        ),
    ]
