# Generated by Django 5.2.5 on 2026-04-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_topproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aboutMe',
        ),
        migrations.DeleteModel(
            name='aboutMeExperiences',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='category',
        ),
        migrations.DeleteModel(
            name='MoreExperience',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Certification',
        ),
        migrations.DeleteModel(
            name='CertificationCategory',
        ),
    ]
